name: Ubuntu

on:
  push:
    branches: [ Linux-support ]
  pull_request:
    branches: [ Linux-support ]

jobs:
  Bionic:
    container: 
      image: swift:5.1.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Linux-support
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Update Dependencies
      run: swift package update
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery
